### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by smn** [Lumenaut-Network/pool#6]
Assuming this repo is meant to be an open source project, an OSI approved license would be awesome and will bring clarity to people considering contributing their time.

Stellar itself uses the [Apache 2.0](https://opensource.org/licenses/Apache-2.0) and it may make sense to adopt that to align with Stellar itself.

**Comment by SeiryuZ** [comment]
Done in https://github.com/Lumenaut-Network/pool/pull/7
